#!/bin/sh

echo "Bem vindo ao instalador de batida de ponto\!"
echo ""

echo "Por favor, insira os dados necessários."
echo ""

echo "ACCOUNT:"
read account
export AHGORA_ACCOUNT=$account

echo "IDENTITY:"
read identity
export AHGORA_IDENTITY=$identity

echo ""

chmod +x ahgora

read -p "Deseja criar um link simbolico? (poder executar o comando de qualquer lugar) [Y/n]? " -n 1
echo ""
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    echo "Criando link..."
    sudo ln -sf $PWD/ahgora /usr/bin/ahgora
fi

echo "Pronto, script preparado! :-)"
